
const { createClient } = require('@supabase/supabase-js');
const OpenAI = require('openai');
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
const openaiKey = process.env.OPENAI_API_KEY;

if (!supabaseUrl || !supabaseKey || !openaiKey) {
    console.error('Missing credentials');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);
const openai = new OpenAI({ apiKey: openaiKey });

// Prompt Constant (Simplified version of what's in course_generator_prompt.ts)
const SYSTEM_PROMPT = `
You are "The Architect", the supreme intelligence of the Upgrade! OS.
Your goal is to design a transformation course layout (syllabus).

Structure:
1. "Propósito del Upgrade" (Why this matters)
2. "Contexto" (Scenario)
3. "Concepto Central" (Core idea/framework)
4. "Vocabulario Clave" (New words)
5. "Mnemotecnia / Framework" (Mental tool)
6. "Comportamientos Actualizados" (Observable changes)
7. "Workshop / Práctica Guiada" (Action)
8. "Aplicación por Contexto" (Real life)
9. "Verificación de Upgrade" (Checklist)
10. "Cierre y Siguiente Paso" (Synthesis)

Output JSON only:
{
    "axis_id": "string",
    "syllabus": [ { "title": "...", "duration": "...", "desc": "..." } ]
}
Make descriptions punchy, modern, and aligned with the Upgrade! philosophy (Human, Leadership, Co-creation).
`;

async function main() {
    console.log('Fetching courses that need population...');

    // Find courses generated by Seed 
    const { data: courses, error } = await supabase
        .from('courses')
        .select('*, categories(axis_id)')
        .eq('origin_topic', 'Seed Data'); // Only standard courses
    // .is('ai_metadata', null); // Or check if not already AI generated?
    // Actually, let's just do ALL seed data courses to be sure.

    if (error) {
        console.error("Error fetching courses:", error);
        return;
    }

    console.log(`Found ${courses.length} seeded courses.`);

    // Let's do a subset for testing, OR all of them?
    // 61 calls is a lot for one go. Let's do the first 5 to demonstrate.
    // The user said "populate the courses", implying all, but let's be safe.
    // I will do 5 from each axis.

    // Filter out ones that already have AI metadata if possible?
    const coursesToUpdate = courses.filter(c => !c.ai_metadata);
    console.log(`${coursesToUpdate.length} need AI content.`);

    if (coursesToUpdate.length === 0) {
        console.log("All seeded courses already have AI metadata. Exiting.");
        return;
    }

    // Process loop
    for (const course of coursesToUpdate) {
        console.log(`\nGenerating for: "${course.title}" (${course.categories?.axis_id})`);

        try {
            const axisId = course.categories?.axis_id || 'human'; // Fallback

            const completion = await openai.chat.completions.create({
                messages: [
                    { role: "system", content: SYSTEM_PROMPT },
                    { role: "user", content: `Tema: "${course.title}". Descripción actual: "${course.description}". Eje: ${axisId}` }
                ],
                model: "gpt-4o-mini",
                response_format: { type: "json_object" },
                temperature: 0.7
            });

            const content = completion.choices[0].message.content;
            const result = JSON.parse(content);

            // Validate result
            if (!result.syllabus || result.syllabus.length < 5) {
                console.warn("Invalid AI response, skipping update.");
                continue;
            }

            // Update DB
            const { error: updateError } = await supabase
                .from('courses')
                .update({
                    syllabus: result.syllabus,
                    ai_metadata: {
                        model: "gpt-4o-mini",
                        prompt_version: "script-v1",
                        generated_at: new Date().toISOString()
                    },
                    // We might also update description if the AI provides a better summary, but we didn't ask for it in top level JSON.
                    // Let's keep the manual description from the seed as it was handwritten by the author.
                })
                .eq('id', course.id);

            if (updateError) {
                console.error("Failed to update DB:", updateError);
            } else {
                console.log("✅ Success!");
            }

            // Wait to avoid rate limits
            await new Promise(resolve => setTimeout(resolve, 1000));

        } catch (e) {
            console.error("Generation failed:", e.message);
        }
    }
}

main();
