name: Deploy to Railway

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Railway Deploy
        run: railway up --service aris-railway-production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
